#
#
# Exisiting Components:
#     - cwd
#     - svn
#     - prompt
#     - user
#
---  # Component Order
component_order:  # default order
    - cwd
    - svn
    - prompt

# Style options:
#     - normal
#     - bold
#     - italic
#
# Color options:
#     - red
#     - blue
#     - yellow
#     - black
#     - white
#     - green
#

cwd:  # default
    style: bold
    color: yellow

svn:
    style: bold
    color: yellow
    sorround:
        left: "["
        right: "]"

prompt:
    style: bold
    color: blue
    symbol: "Î»"
